---
title: "White-faced Darter distribution in the Scottish Highlands is related to wet pine forests"
authors: "Matthew Geary & Achaz von Hardenberg
output:
  pdf_document: 
    latex_engine: xelatex
  html_notebook: default
---

White -faced darter distribution in the Scottish Highlands
===========================================================


Introduction
--------------

An objective often cited to explain the utility of understanding species distributions is for the planning of future surveys (REF) and identifying priority areas for conservation action (REF). As well as being useful for species which are poorly known (REF), or inhabit remote locations (REF) so their populations cannot be effectively monitored there are also species which are well know locally but poorly known over wider areas (REF). Monitoring projects for various taxa have shown that biases can occur regarding the distribution of moinitoring effort or species records (REF). This can be a particular problem for understudied taxa where expertise may be localised or restricted to only a few individuals (REF). 

### Using SDMs and coccupancy for conservation prioritization and survey locations

Where species are monitored sporadically (REF), through only incidental sightings (REF) or are extremely rare (REF) we might only have access to presence records for a species. Similary, where taxa are monitored using volunteer recording schemes thereis a trade-off between the information content of the data and the ease with which volunteers can complete records in the field (REF). More complex surveys which result in information-rich data require more experienced/trained recorders and can limit the geopgraphic coverage of the survey (REF). On the other hand, simpler more widespread surveys can introduce issues with data quality due to inexperienced observers or patch records (REF). Information-linited data restrict the methods available to investigate species distributions (REF) and can make it hard to project models onto unknown or underrecorded areas (REF). In particular, this is a problem because, although species presence can be established, there are likely to be few or low quality records of species absence (REF). For other species, however, more comprehensive monitoring programmes exist and this allows methods which can incorporate uncertainty of absence and produce more robust estimates of species occupancy across a landscape (REF). 

### Importance of incorporating imperfect detection

Issues regarding imperfect detection of species in the field are well established in the literature (REF). Where species are rare, localised or survey coverage is spatially or temporally patchy the inability to detect absence of a species is particulary problematic. However, using data from long-term recording schemes or those involving large numbers of volunteers provides the opportunity for repeat visits to a site even if this was not originally part of the survey design (REF). We can also infer absence from detailed recordings from experienced observers who regularly record complete lists, records of all species which are present at a site (REF). Recent advances in occupancy modelling have established that surrogate species can be used to infer absence under some recording schemes. EXAMPLE REF. These advances provide an opportunity to increase the value of data from widepsread recording shcemes (REF), 'presence only' datasets (REF) and for neglected taxa where recording is sparse (REF).

Globally conservation research, intervention and management is biased towards high-profile taxa (REF). Disproportionate effort is afforded to mammals and birds in particular whereas invertebrates, which make up the majority of species present on earth, recieve relatively little attentiony to(REF). Some of this bias can be explained by human preference for 'charismatic' species and by an understandable tendency to build on previous conservation success. However, the body of literature on butterfly conservation (REF), ecology (REF) and behaviour (REF) demonstrates the potential for invertebrate conservation. Odonata, dragonflies and damselflies, are also relatively 'charismatic' invertebrate species and have recieved some considerable attention in the scientific literature (REF - model organisms book). However, Odonata conservation is still in its relative infancy (REF) and even in countries with relatively few species (REF) where conservation is seen as a social priority (REF) such as the U.K. there is relatively little conservation action specifically for Odonata (REF). For example BUTTERFLY vs DRAGONFLY example. Priorities highlighted on the UK red list for Odonata include fully establishing species distributions and habitat requirements for several species (REF - red list), particularly those which inhabit remote areas.   

White-faced darter (_Leucorhinnia dubia_) are a lowland bog specialist dragonfly species (REF). In great Britain their distribution is heavily biased towards the Scottish highlands (REF). There are several populations further south, in England, which have been the focus of conservation attention, including reintroduction programmes (REF). The Scottish populations, on the other hand, are thought to be declining (are they???) but only recieve localised conservation intervention (REF). The species is well  monitored in some areas but their patchy distributions across a large landscape means that the species is thought to be underrecorded (REF). Here we aim to use a combination of occupancy models to model the distribution of White-faced darter in the Scottish highlands in order to predict areas of occurence and investigate habitat drivers of this distribution. 

## Current research and habitat knowledge

Methods
--------

##Data

White-faced darter presence records between 2000 and 2015 were obtained from the British Dragonfly society. These records represent incidental records rather than a stratified recording scheme and can represent flying adults, larvae or exuvia. Additionally, the records related towhite-faced darter refer only to presence of the species. Absence was inferred from records of another species, Four-spotted chaser (_Libellula quadrimaculata_) which is also in flight during the flight period of white-faced darter. Four-spotted chaser is a conspicuous species which occurs in similar habitats to White-faced darter and is visually very different. Records of Four-spotted chaser imply that the sight was visited for the purpose of dragonfly recording and so the lack of records for White-faced darter on the same date suggest absence of this species (REF). In fact, this absence may be an overestimate as Four-spotted chaser have higher detectability than White-faced darter due to their territorial patrolling behaviour (REF). 

~Importance of using information from both Exuvia and adults~
White-faced darter, and dragonflies more generally, spend the majority of their lifespans as larvae and only existas breeding adults for a short period of time (REF). Habitat preference therefore, involves two separate processes, firstly that females select habitat which they percieve to be suitable for oviposition and secondly, that the habitat selected is truly suitable for larvae to survive to adulthood. Indeed, this problem and the implications it presents for surveying dragonfly species has been noted in the literature with XXXX (REF) suggesting that only records of exuvia can demonstrate successful breeding and therefore more fully represent the population. However, exuvia counts can be difficult both in terms of logistics (REF) and detectability (REF) and may not fully represent the movements and habitat preferences of adult dragonflies (REF). We chose to use data from both of these sources along with data from larval surveys. As exuvia counts were much rarer for this species than counts from adult transects (XXX conpared with XXXX) our method integrates models of exuvia and adult occupancy.

##Environmental variables

Environmental variables used to predict occupancy of White-faced darter were downloaded from the EUNIS land-cover classification for Scotland (SOURCE AND LICENCE). We used established EUNIS classes for HAB, HAB and HAB to produce variables representing HAB VARIABLES LIST.

##Occupancy model

Results
--------

## Model

Discussion
------------

## Model results

## Areas for survey or protection

## Model evaluation

## Use of method and surrogate species

## Conservation implications for WFD

## Potential future work

## Conclusions
